### ISSUE TITLE
Prevent blinking while typing

### ISSUE THREAD

**Issue by WoodyWoodsta** [amio/hyper-blink#2]
A bit distracting to have the cursor blinking when you are typing :yum: 

Nice idea though! Should probably be a part of hyperterm itself!

**Comment by amio** [comment]
Yeap, working on it 💃

**Comment by amio** [comment]
It should work by now. 👻

**Comment by CrazyPython** [comment]
@amio just installed, still blinks.

**Comment by amio** [comment]
@WoodyWoodsta Blinks while typing? It seems fine on my laptop, HyperTerm 0.7.1 on OSX 10.11, which version are you using?

**Comment by CrazyPython** [comment]
@amio Also on OSX. Hyperterm latest, just installed so it should be latest.

**Comment by amio** [comment]
@WoodyWoodsta It's weird, I've no idea how it happened, if you have any further information please let me know.
