### ISSUE TITLE
Can't paste multiple times.

### ISSUE THREAD

**Issue by lucasmouilleron** [amio/hyper-blink#4]
If pasted once, it is not possible to paste again, unless return is stroked.

In python -i or ipython, the behaviour is a tiny bit different : 
If pasted once, can't paste subsequently unless one or more chars are pressed (sometimes including, sometimes excluding "return")

**Comment by amio** [comment]
Sorry for not seeing this!
While I tried in python repl, haven't found that problem, I'm using 0.7.1.36 on OSX 10.11.
Which version are you using?

**Comment by amio** [comment]
Close this for now, I'll reopen it if there's any further information. Thanks @lucasmouilleron
