### ISSUE TITLE
Slow blinking down

### ISSUE THREAD

**Issue by CrazyPython** [amio/hyper-blink#5]
It's a bit too fast for me. Any way to slow it down?

**Comment by amio** [comment]
Currently it's the same frequency as Mac Terminal app, 1 sec a loop.
Maybe we can add an entry to configuration file for this, but I'm not sure is it much needed.

What's your prefer timing?

**Comment by CrazyPython** [comment]
@amio it seems faster than terminal.app...

**Comment by amio** [comment]
While, at least I can guarantee that this plugin blinks per second :D

**Comment by amio** [comment]
I've made a rough counting, both plugin & Terminal blinks 20 times in 20.x seconds. Not very accurate but seems the same.

**Comment by amio** [comment]
@CrazyPython I've slightly adjusted the animation, making it smoother, which feels slower too(to me at least). See if you feel it slower?
